[server]
# Ignore data directory to prevent file watcher issues
fileWatcherType = "poll"
headless = false

[runner]
# Don't watch data directory
fastReruns = true

[global]
# Disable file watcher for these patterns
disableWatchdogWarnings = true

[theme]
primaryColor = "#4ECDC4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"